(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#A7BCBF",
	manifest: []
};



// symbols:



(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#241F20").s().p("AASErQhIgfg7gzQhBg5gVg/Qgph4BVimQAhhCAngmQAngoAXAMQAZANgEAZQgBAPgOAVQgpA9gcBAQg3B8AbBHQAbBIBaAmQAuAUBLAMQBfARgIApQgJAug6AFIgOABQgxAAhBgag");
	this.shape.setTransform(-26.7,-7.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#241F20").s().p("AhuBbQgbgNgWgQIgRgNIg1AxQg+AsgqgbQgugdAbhGQAUgyA0g7QAjgnAeADQAPABAaATQAEADARAXQASAaASARQA/A5BjALQCMAQBUiGQALgTAOgJQAagRAcASQAUANgHAdQgEASgLARQgrA6g6AsQhWBDhWABIgJAAQhcAAhSgng");
	this.shape_1.setTransform(-68.4,34.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#241F20").s().p("AgxgGIAEgjQAEAiAQANQAJAIAHABQAYAHAUgUQAKgIAFgLQgMAsgcAMIgYADQghgMgCgkg");
	this.shape_2.setTransform(50.3,-43.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#241F20").s().p("AgxgGIAEgjQAEAiAQANQAJAJAHAAQAYAHAUgUQAKgIAFgMQgMAtgcANIgYACQghgMgCgkg");
	this.shape_3.setTransform(30.7,-47.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#241F20").s().p("AgOAxQg/gUgMgpQgDgNACgOIADgLQANAnAhASQARALAOACQAuANAhgSQARgKAGgJQgMAvgxAIg");
	this.shape_4.setTransform(36.2,-26.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#241F20").s().p("AgLBtQglgHAjhpIAphpIADBwQgFBpggAAIgFAAg");
	this.shape_5.setTransform(37.5,-37.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#241F20").s().p("AgBAHQgGgDACgFQABgDADgBQABgCACABQADABABADQABACgBACQgBAFgFAAIgBAAg");
	this.shape_6.setTransform(23.9,-33.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#241F20").s().p("AgBAHQgGgCACgGQACgGAFABQADABABADQABACgBACQgCAFgEAAIgBAAg");
	this.shape_7.setTransform(20.1,-34.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#241F20").s().p("AgBAHQgGgDACgFQABgDADgBQABgCACABQADABABADQABACgBACQgBAFgFAAIgBAAg");
	this.shape_8.setTransform(23.1,-37.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#65CD69").s().p("AjPIyQgcgJgogXQgYgOhlgRQhUgOgbgmQgSgZABheQABhbASh2QAskcBYiFQBYiEByhPQBmhIA+AIQBAAIA2AtQA7AxA1AMQA1ANBAgHQA3gGA4AUQA+AWAPBQQAOBIgcBhQgYBShyC/QhjCng2BFQhMBhgtAqQhfBWhZAHIggABQgyAAgngMg");
	this.shape_9.setTransform(4.8,-19.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#241F20").s().p("AgTFTQgygDgRgSQgMgOAEgYQAWgyAQgvQAfhcgKhSQgNhvhoinQgKgPADgSQAEgXAZgLQAVgIAYATQAOALAJAPQAkAyAeBKQAiBMAOBBQANA1gHBgQgDAxgGAlIA1AAQA1AJAFAuQAFAyhBAVQgmAMg2AAIgbAAg");
	this.shape_10.setTransform(12.8,63.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#241F20").s().p("AhPCtQhWgchAhpQgphCgahXQgFgQAFgSQAFgVASgJQAVgKAQAOQAKAKALAaQAeBLAkA1QAzBMA0AOQBDAUBQgxQAngXA0gxQBBhBAbAfQAeAggdAvQgbAuhAAqQhBAqhHASQgoAJghAAQgiAAgegJg");
	this.shape_11.setTransform(74.8,3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#644424").s().p("AgGCqIgUgNQAthMglh9QgThAgcgwIBMgXQA+BmgICGQgCAxgMAmQgKAjgKABIgFAAQgOAAgSgKg");
	this.shape_12.setTransform(34,-79.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E35").s().p("AiLgsIAigIQApgIAmAAQB4ABAuBXQgnAcg3AFIgRAAQhhAAhHhpg");
	this.shape_13.setTransform(20.3,-83.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.8,-97.7,209.6,195.5);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C67400").s().p("AAAA/QjpAAgOgDQgYgEgMgEQgVgHgggSQgwgbgHgeQgFgYAJgGQAHgEALAEIAXAOQAWAOAQAMQAZASAYAFQAQAFAlADQAmAECogDIAAAAQCpADAmgEQAlgDAQgFQAYgEAZgTQAQgMAWgOIAXgOQALgEAGAEQAKAGgFAYQgHAegwAbQggASgVAHQgMAEgYAEQgPADjpAAg");
	this.shape.setTransform(35.4,6.4);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		/* Animate Vertically
		Moves the symbol instance vertically on the stage by decreasing or increasing its y property within an Tick event.
		
		Instructions:
		1. The default direction of the animation is down.
		2. To change the direction of the animation to up, change the number 10 below to a negative value.
		3. To change the speed at which the symbol instance moves, change the number 10 below to the number of pixels you want the symbol instance to move in each frame.
		4. Because the animation uses an Tick event, it progresses only when the playhead moves to a new frame. The speed of the animation is also affected by the document frame rate.
		*/
		
		this.addEventListener("tick", fl_AnimateVertically.bind(this));
		
		function fl_AnimateVertically()
		{
			this.movieClip_3.y+=10;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(5));

	// Layer 1
	this.movieClip_3 = new lib.Symbol9();

	this.timeline.addTween(cjs.Tween.get(this.movieClip_3).to({_off:true},1).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.8,-97.7,209.6,195.5);


// stage content:



(lib.myProject = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"Frame 2":0,"Frame 4":42,"Frame 1":0,"Frame 1":12});

	// timeline functions:
	this.frame_1 = function() {
		/* Play a Movie Clip
		Plays the specified movie clip on stage.
		
		Instructions:
		1. Use this code for movie clips that are currently stopped.
		*/
		
		movieClip_2.play();
	}
	this.frame_101 = function() {
		/* Play a Movie Clip
		Plays the specified movie clip on stage.
		
		Instructions:
		1. Use this code for movie clips that are currently stopped.
		*/
		
		this.movieClip_1.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(100).call(this.frame_101).wait(3));

	// Layer 11
	this.movieClip_2 = new lib.Symbol8();
	this.movieClip_2.setTransform(269.8,147.9);

	this.timeline.addTween(cjs.Tween.get(this.movieClip_2).to({_off:true},42).wait(62));

	// Layer 10
	this.instance = new lib.Symbol6();
	this.instance.setTransform(273,232.4,1,1,0,0,0,39.4,6.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:35.4,x:269},0).wait(40).to({_off:true},1).wait(62));

	// Intro 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0033CC").s().p("AgEAOQgKgFgBgCQgBgCAEgIIAFgMQABAAAAgBQAAAAABAAQAAgBABAAQABAAABAAIAKADQAIABAAAEQABACgDAGQgDAEAAADIAAAFQgBAGgCABIgBAAQgEAAgHgEg");
	this.shape.setTransform(554.4,177.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0033CC").s().p("AACA9IgFgCIgIgBQgDgBgEgDIgIgLIgGgLIgEgHQAAgDAFgBIADgBIAPACIAKACIACALQABAKACAAQAAAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIABgKQAAgQgHgEIgQgIQgFgEgEgCQgEgEgBgGQgCgHAAgJQAAgLAGgKQADgFADgDQAEgDAEgBQAEgBARAIIALADQAGABADADQAEAEAAAKIAAAPIABAIQAAAGgEABQgEAAgIgDQgIgDgDgDIgBgPQgBgNgCAAQgCAAgCAIQgCAHAAAJQgBAFACAEQABADACABIASAJQAKAGAEAFQACAEABAFQACAFAAAHQAAALgIAGQgDAEgGABQgFACgHAAg");
	this.shape_1.setTransform(548.5,173.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0033CC").s().p("AgKA4QgOgFgEgFQgLgPAAgbQAAgXAKgTQAFgLAHgFQAHgFAJgBQAEAAAJAEIAKAFIAIAGQABACACAJQACAJAAAKQAAAGgBAFQgBAEgCABIgVAGIgTACQgBAKADAKQADALADAAQACABAFgHQAFgGACgEIADgMQAEgBAJAEQAJADACADQACADgKAPQgFAIgFAFQgFAGgFACIgEABQgIAAgKgFgAgDgbIgFALIgCAKQAJAAADgEQACgBABgFIAAgOQAAgIgBAAQgDAAgEALg");
	this.shape_2.setTransform(539.9,173.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0033CC").s().p("AAABTIgNgFQgEgEAAgDIABgCIABgEIAAiLIgBgCIgBgDQAAgEAIgCIAIAAIALACQAIADAAAEIgBAEIgBADIgDAMIAAB5IACAEIABADQAAANgFABIgBABIgKgDg");
	this.shape_3.setTransform(533.2,171.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0033CC").s().p("AgcBUIgMgEQgFgBgBgFQAAgCACgGIACgHIAAiAQAAgGgBgCQgDgFABgCQABgCAEAAIAOACIALACQAEABABAEIABADQAAAIgDAQIAKgTQAEgMAGABQATAEAKAMQAKANAAAUQAAAXgNAVQgGAMgGAHQgHAIgHADIgEABQgDAAgCgDIgLgJIAAAnIACAFIACAGQAAAFgGAAQgFAAgJgDgAgLAWQALgFAHgRQAJgPAAgOQAAgRgNgCIAAAAQgFAAgJBGg");
	this.shape_4.setTransform(525.7,174.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0033CC").s().p("AgcBUIgMgEQgFgBgBgFQAAgCACgGIACgHIAAiAQAAgGgBgCQgDgFABgCQABgCAEAAIAOACIALACQAEABABAEIABADQAAAIgDAQIAKgTQAEgMAGABQATAEAKAMQAKANAAAUQAAAXgNAVQgGAMgGAHQgHAIgHADIgEABQgDAAgCgDIgLgJIAAAnIACAFIACAGQAAAFgGAAQgFAAgJgDgAgLAWQALgFAHgRQAJgPAAgOQAAgRgNgCIAAAAQgFAAgJBGg");
	this.shape_5.setTransform(515.2,174.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0033CC").s().p("AgXA6IgIgHIgLgMQgEgGAAgFIABgCQABgKAGgIQAGgIAKgGQAPgMAYgNQAAgFgDgDQgCgBgMAGQgKAGgFAEIgFAEQgEACgCAAQgDgBgHgHQgHgGgBgCQgBgGAFgDIAIgCIAPgIIAOgGIAKgCQAFAAAFAEIALAJIALAJQAGAGAAAFIAABKQACAEAAADQAAACgCACQgDACgCAAIgUgEQgHgDgBgDIAAgBIAAgCIACgCIAAgCIABgHQgDABgFAJQgFAIgCADQgGAHgIAAQgFAAgEgFgAAAAGIgKANQgEADgEAHQgEAHAAADQAAAAAAABQAAAAAAAAQABAAAAAAQAAAAAAAAQACABAFgFIAMgOIAKgPQAFgHACgEQgKAEgFAGg");
	this.shape_6.setTransform(504.5,173.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0033CC").s().p("AgEBHQgMgDgBgDIABgGIACgIIAAhFIgGAAQgEAAgFgGQgHgGABgFQgBgDADgCQADgDACAAIAOAAIAAgSQgDgEAAgEQABgEADgBIAFAAQAHAAAJABQAKADACADIABACQAAACgDAEIgDAFIAAALIAGAAQADABAGAGQAGAIAAADQAAADgCADQgDADgCAAIgCAAQgCgBgKAAIAABNIACADIAAAGQABAGgJABQgDAAgKgFg");
	this.shape_7.setTransform(490.5,171.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0033CC").s().p("AAYA8QgNgDgCgDQAAgDABgEIACgIIgBgFQgDAKgFAIQgDAFgBACQgEACgDAAQgHAAgLgEQgLgFgBgEQgFgNgBhPQgBgEAAgEQAAgGAEgCIAGgBQAGAAAKACQAJACACACIABADQAAACgDAFQgDAFAAACQAABNABABQABAAAEgFIAHgOQAGgKACgHQADgGAAgFIAAglQgCgDAAgDQAAgEABgDQADgDADgBIACAAQAGAAAKACIALAEIABAEIgBAFIgDADIAABbIACAFIABAEQAAAEgHABIgBAAIgNgCg");
	this.shape_8.setTransform(481.5,173.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0033CC").s().p("AAKA+IgOgDIgPgDQgGgCgEgFQgFgFgDgIQgEgHgBgJQgCgJAAgKQAAgJACgJIAFgSQADgJAFgGQAFgHAHgEIAGgBIAOADQAHAAANACQAFADAEAFQAFAFADAIQAFAOAAAUQAAAMgCALQgDAMgEAKQgFAKgHAFQgFAFgGAAIgDgBgAgDgkQgDAEgCAGQgEARAAAIQABARACAKQAEAPAFABQAEABAFgPQAFgQAAgQQAAgKgDgKQgDgPgIAAQgBAAgCADg");
	this.shape_9.setTransform(471.7,173.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0033CC").s().p("AgeBTQgMgDgCgDQgBgCADgFQABgCAAgGIAAiFIgCgDQgCgDABgCQABgHAHAAQAHAAAKAEQALAEACAEQABACgDAEIgCAIIAAAhQAOgQAKABQAHABAIAGIAHAHIAFAIQAFAJAAAMIgCAUIgFAVIgIASIgJAOIgBAEIgCAEQgDACgHAAQgGAAgDgDIgJgHIABAEQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgCAEgDAAIgCABQgEAAgLgEgAABgHQgIAHgCAGIAAA2IAEAEQAEABACgIQAEgHAEgPIAHgcQADgKAAgKIgBgGQgIADgJAJg");
	this.shape_10.setTransform(461.8,171);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0033CC").s().p("AgXA6IgIgHIgLgMQgEgGAAgFIABgCQABgKAGgIQAGgIAKgGQAPgMAYgNQAAgFgDgDQgCgBgMAGQgKAGgFAEIgFAEQgEACgCAAQgDgBgHgHQgHgGgBgCQgBgGAFgDIAIgCIAPgIIAOgGIAKgCQAFAAAFAEIALAJIALAJQAGAGAAAFIAABKQACAEAAADQAAACgCACQgDACgCAAIgUgEQgHgDgBgDIAAgBIAAgCIACgCIAAgCIABgHQgDABgFAJQgFAIgCADQgGAHgIAAQgFAAgEgFgAAAAGIgKANQgEADgEAHQgEAHAAADQAAAAAAABQAAAAAAAAQABAAAAAAQAAAAAAAAQACABAFgFIAMgOIAKgPQAFgHACgEQgKAEgFAGg");
	this.shape_11.setTransform(451.7,173.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0033CC").s().p("AghA8QgKgDgCgBIAAgEQgBgCADgDIACgDIAAhbIgCgFQAAAAAAgBQAAAAgBgBQAAgBAAAAQAAgBAAAAQABgEAGgBQADgBALADQANADACADQABADgCAEIgCAIIABAFQADgKAFgIQAFgJAGAAQAHAAALAEQAKAFADAEQACAGABAYQACAVAAApIABAIQABAGgFACIgFABQgHAAgKgCQgIgCgDgCIgBgDQAAgCADgFQAEgFAAgCQgBgzgBgbQgCgBgLATQgLAUABAJIAAAlQACADAAADQAAAEgBADQgCACgEACIgCAAQgGAAgKgCg");
	this.shape_12.setTransform(436.6,173);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0033CC").s().p("AAKA+IgOgDIgPgDQgGgCgEgFQgFgFgDgIQgEgHgBgJQgCgJAAgKQAAgJACgJIAFgSQADgJAFgGQAFgHAHgEIAGgBIAOADQAHAAANACQAFADAEAFQAFAFADAIQAFAOAAAUQAAAMgCALQgDAMgEAKQgFAKgHAFQgFAFgGAAIgDgBgAgDgkQgDAEgCAGQgEARAAAIQABARACAKQAEAPAFABQAEABAFgPQAFgQAAgQQAAgKgDgKQgDgPgIAAQgBAAgCADg");
	this.shape_13.setTransform(426.9,173.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0033CC").s().p("AACA9IgFgCIgIgBQgDgBgEgDIgIgLIgGgLIgEgHQAAgDAFgBIADgBIAPACIAKACIACALQABAKACAAQAAAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIABgKQAAgQgHgEIgQgIQgFgEgEgCQgDgEgCgGQgCgHAAgJQAAgLAGgKQADgFADgDQAEgDAEgBQAEgBARAIIALADQAGABADADQAEAEAAAKIAAAPIABAIQAAAGgEABQgEAAgIgDQgIgDgDgDIgBgPQgBgNgCAAQgCAAgCAIQgCAHAAAJQgBAFACAEQABADACABIASAJQAKAGADAFQADAEABAFQACAFAAAHQAAALgIAGQgDAEgGABQgFACgHAAg");
	this.shape_14.setTransform(418,173.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0033CC").s().p("AACA9IgFgCIgIgBQgEgBgDgDIgIgLIgGgLIgEgHQAAgDAFgBIADgBIAPACIAKACIACALQABAKACAAQAAAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIABgKQAAgQgHgEIgQgIQgFgEgEgCQgDgEgCgGQgCgHAAgJQAAgLAGgKQADgFAEgDQADgDAEgBQADgBASAIIALADQAGABACADQAFAEAAAKIABAPIAAAIQAAAGgEABQgEAAgIgDQgIgDgDgDIgBgPQgBgNgCAAQgCAAgCAIQgCAHAAAJQAAAFABAEQABADACABIASAJQAKAGAEAFQACAEABAFQABAFAAAHQABALgIAGQgDAEgGABQgFACgHAAg");
	this.shape_15.setTransform(409.8,173.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0033CC").s().p("AgKA4QgOgFgEgFQgLgPAAgbQAAgXAKgTQAFgLAHgFQAHgFAJgBQAEAAAJAEIAKAFIAIAGQABACACAJQACAJAAAKQAAAGgBAFQgBAEgCABIgVAGIgTACQgBAKADAKQADALADAAQACABAFgHQAFgGACgEIADgMQAEgBAJAEQAJADACADQACADgKAPQgFAIgFAFQgFAGgFACIgEABQgIAAgKgFgAgDgbIgFALIgCAKQAJAAADgEQACgBABgFIAAgOQAAgIgBAAQgDAAgEALg");
	this.shape_16.setTransform(401.2,173.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0033CC").s().p("AAABTIgNgFQgEgEAAgDIABgCIABgEIAAiLIgBgCIgBgDQAAgEAIgCIAIAAIALACQAIADAAAEIgBAEIgBADIgDAMIAAB5IACAEIABADQAAANgFABIgBABIgKgDg");
	this.shape_17.setTransform(394.5,171.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0033CC").s().p("AgKA4QgOgFgEgFQgLgPAAgbQAAgXAKgTQAFgLAHgFQAHgFAJgBQAEAAAJAEIAKAFIAIAGQABACACAJQACAJAAAKQAAAGgBAFQgBAEgCABIgVAGIgTACQgBAKADAKQADALADAAQACABAFgHQAFgGACgEIADgMQAEgBAJAEQAJADACADQACADgKAPQgFAIgFAFQgFAGgFACIgEABQgIAAgKgFgAgDgbIgFALIgCAKQAJAAADgEQACgBABgFIAAgOQAAgIgBAAQgDAAgEALg");
	this.shape_18.setTransform(556.5,148.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0033CC").s().p("AgEA+QgRgFgCgCIgBgFIAAgEIgOguQgFgWgCgcIgBgDIAAgEQAAgFAEgBQACgBAOAEQANADABADIABADIgBAEIgCAFIAFAbQADARAEAQIAJgrIAHgbIABgIQACgDAEgCQACgBAKAFQAMAFACAEQgHAUgLAnQgJAkABAFIAAAKQgBAGgEABIgCABQgGAAgMgEg");
	this.shape_19.setTransform(546.9,148.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0033CC").s().p("AALBPQgHAAgJgDQgLgDgCgDQgBgCADgFQABgDAAgIIAAhSIgCgKQAAgCAHAAQAGAAAJADQALAEACADIABACIgDAGIgCAGIAABPQAAACACADIADAEQABAHgGACgAgBgxQgPgFgBgCIgBgDQAAgGADgGQADgGAEgBQAFgBAJAEQALAFACAEIABACIgCALQgCAIgCAAIgBABQgEAAgKgFg");
	this.shape_20.setTransform(539.5,146.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0033CC").s().p("AgEBIQgMgFAAgCIABgHIABgHIAAhEIgHAAQgDAAgGgHQgFgGAAgEQgBgEADgCQADgDACABIAOAAIAAgSQgCgFAAgEQAAgFADgBIAFAAQAIAAAIACQAJADADACIABADQAAACgDAEIgDAGIAAALIAGAAQACgBAHAIQAGAHAAADQAAADgCADQgCADgDAAIgBAAQgDgBgKAAIAABNIACADIABAGQAAAGgJAAQgDAAgKgDg");
	this.shape_21.setTransform(533.2,146.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0033CC").s().p("AAAA+QgLAAgQgLQgIgFgDgLQgDgLgBgRQAAgYAIgUQAJgXAMgBQAKAAAMAFQAPAGAEAHQAEAGABAKIgBAHIAAAHIABAFQAAAGgHAAQgHAAgHgCQgIgDgCgFQAAgCACgDIACgFIAAgHIgBgJQAAgBgBgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQgFgBgEAUQgEAXAAANQAAANACAGQABAHADAAQAFABAFgLQAGgJAAgDIABgHQACgGAGABIANAEQAIAFABACIABADQgBAEgGAGQgFAMgFAFQgEAGgGAEQgFADgIACg");
	this.shape_22.setTransform(524.7,148);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0033CC").s().p("AgXA7IgIgIIgLgMQgEgFAAgGIABgDQABgJAGgIQAGgIAKgGQAPgLAYgNQAAgHgDgBQgCgCgMAGQgKAFgFAEIgFAFQgEACgCgBQgDgBgHgGQgHgHgBgCQgBgFAFgDIAIgCIAPgJIAOgFIAKgDQAFAAAFAGIALAJIALAIQAGAGAAAFIAABJQACAGAAABQAAAEgCACQgDABgCAAIgUgEQgHgCgBgDIAAgCIAAgDIACgCIAAgBIABgHQgDACgFAHQgFAJgCAEQgGAFgIAAQgFAAgEgDgAAAAGIgKAMIgIALQgEAHAAADQAAAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAQACgBAFgEIAMgNIAKgRQAFgGACgEQgKAEgFAGg");
	this.shape_23.setTransform(514.9,148.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0033CC").s().p("AgZA7QgLgEAAgGIABgGIACgHIAAhNIgCgLQAAgHAFgBIAGgBQAHAAAIACQAHADACACIAAACIgDAKIAAAKIAIgSQAGgKADgBQAEgBAJAGQAJAGABAEQABADgDACIgEADIghAyIABAhIABAFIAAAGQAAAEgCABIgGABQgIAAgJgDg");
	this.shape_24.setTransform(506.1,148.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0033CC").s().p("AgKA4QgOgFgEgFQgLgPAAgbQAAgXAKgTQAFgLAHgFQAHgFAJgBQAEAAAJAEIAKAFIAIAGQABACACAJQACAJAAAKQAAAGgBAFQgBAEgCABIgVAGIgTACQgBAKADAKQADALADAAQACABAFgHQAFgGACgEIADgMQAEgBAJAEQAJADACADQACADgKAPQgFAIgFAFQgFAGgFACIgEABQgIAAgKgFgAgDgbIgFALIgCAKQAJAAADgEQACgBABgFIAAgOQAAgIgBAAQgDAAgEALg");
	this.shape_25.setTransform(497.5,148.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0033CC").s().p("AgEBIQgMgFAAgCIABgHIABgHIAAhEIgHAAQgDAAgGgHQgFgGAAgEQAAgEACgCQADgDACABIAOAAIAAgSQgCgFAAgEQgBgFAEgBIAFAAQAIAAAIACQAJADADACIABADQAAACgCAEIgEAGIAAALIAGAAQACgBAHAIQAGAHABADQgBADgCADQgCADgDAAIgBAAQgDgBgKAAIAABNIACADIABAGQgBAGgHAAQgEAAgKgDg");
	this.shape_26.setTransform(489,146.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0033CC").s().p("AggA8QgLgDgBgBIgCgEQAAgCADgDIACgDIAAhbIgBgFQgBAAAAgBQAAAAAAgBQgBgBAAAAQAAgBABAAQABgEAEgBQAEgBALADQANADACADQABADgCAEIgCAIIAAAFQAEgKAFgIQAEgJAIAAQAGAAALAEQALAFABAEQADAGACAYQABAVAAApIACAIQgBAGgEACIgFABQgHAAgKgCQgJgCgBgCIgBgDQAAgCACgFQADgFAAgCQAAgzgBgbQgDgBgKATQgLAUAAAJIAAAlQAEADAAADQAAAEgDADQgBACgDACIgDAAQgFAAgKgCg");
	this.shape_27.setTransform(479.9,148.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0033CC").s().p("AALBPQgHAAgJgDQgLgDgCgDQgBgCADgFQABgDAAgIIAAhSIgCgKQAAgCAHAAQAGAAAJADQALAEACADIABACIgDAGIgCAGIAABPQAAACACADIADAEQABAHgGACgAgBgxQgPgFgBgCIgBgDQAAgGADgGQADgGAEgBQAFgBAJAEQALAFACAEIABACIgCALQgCAIgCAAIgBABQgEAAgKgFg");
	this.shape_28.setTransform(472.5,146.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0033CC").s().p("AggA8QgLgDgBgBIgCgEQAAgCADgDIACgDIAAhbIgBgFQgBAAAAgBQAAAAAAgBQgBgBAAAAQAAgBABAAQABgEAEgBQAEgBALADQANADACADQABADgCAEIgCAIIAAAFQAEgKAFgIQAEgJAIAAQAGAAALAEQALAFABAEQADAGACAYQABAVAAApIACAIQgBAGgEACIgFABQgHAAgKgCQgJgCgBgCIgBgDQAAgCACgFQADgFAAgCQAAgzgBgbQgDgBgKATQgLAUAAAJIAAAlQAEADAAADQAAAEgDADQgBACgDACIgDAAQgFAAgKgCg");
	this.shape_29.setTransform(460.1,148.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#0033CC").s().p("AgXA7IgIgIIgLgMQgEgFAAgGIABgDQABgJAGgIQAGgIAKgGQAPgLAYgNQAAgHgDgBQgCgCgMAGQgKAFgFAEIgFAFQgEACgCgBQgDgBgHgGQgHgHgBgCQgBgFAFgDIAIgCIAPgJIAOgFIAKgDQAFAAAFAGIALAJIALAIQAGAGAAAFIAABJQACAGAAABQAAAEgCACQgDABgCAAIgUgEQgHgCgBgDIAAgCIAAgDIACgCIAAgBIABgHQgDACgFAHQgFAJgCAEQgGAFgIAAQgFAAgEgDgAAAAGIgKAMIgIALQgEAHAAADQAAAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAQACgBAFgEIAMgNIAKgRQAFgGACgEQgKAEgFAGg");
	this.shape_30.setTransform(449.9,148.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#0033CC").s().p("AABA9IgFgCIgHgBQgDgBgDgDIgJgLIgHgLIgCgHQAAgDADgBIAEgBIAPACIAKACIACALQABAKABAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIABgKQAAgQgGgEIgQgIQgHgEgCgCQgFgEgCgGQgBgHAAgJQAAgLAGgKQADgFADgDQAEgDAEgBQADgBATAIIAKADQAGABADADQADAEABAKIAAAPIACAIQgBAGgFABQgDAAgHgDQgKgDgCgDIgCgPQAAgNgCAAQgCAAgCAIQgDAHAAAJQABAFABAEQABADACABIASAJQAKAGADAFQADAEABAFQABAFABAHQgBALgHAGQgEAEgFABQgFACgGAAg");
	this.shape_31.setTransform(435.9,148.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#0033CC").s().p("AALBPQgHAAgJgDQgLgDgCgDQgBgCADgFQABgDAAgIIAAhSIgCgKQAAgCAHAAQAGAAAJADQALAEACADIABACIgDAGIgCAGIAABPQAAACACADIADAEQABAHgGACgAgBgxQgPgFgBgCIgBgDQAAgGADgGQADgGAEgBQAFgBAJAEQALAFACAEIABACIgCALQgCAIgCAAIgBABQgEAAgKgFg");
	this.shape_32.setTransform(429.3,146.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#0033CC").s().p("AABA9IgFgCIgHgBQgDgBgDgDIgJgLIgHgLIgCgHQAAgDADgBIAEgBIAPACIAKACIACALQABAKABAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIABgKQAAgQgGgEIgQgIQgHgEgCgCQgFgEgCgGQgBgHAAgJQAAgLAGgKQADgFADgDQAEgDAEgBQADgBATAIIAKADQAGABADADQADAEABAKIAAAPIACAIQgBAGgFABQgDAAgHgDQgKgDgCgDIgCgPQAAgNgCAAQgCAAgCAIQgDAHAAAJQABAFABAEQABADACABIASAJQAKAGADAFQADAEABAFQABAFABAHQgBALgHAGQgEAEgFABQgFACgGAAg");
	this.shape_33.setTransform(417.9,148.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#0033CC").s().p("AALBPQgHAAgJgDQgLgDgCgDQgBgCADgFQABgDAAgIIAAhSIgCgKQAAgCAHAAQAGAAAJADQALAEACADIABACIgDAGIgCAGIAABPQAAACACADIADAEQABAHgGACgAgBgxQgPgFgBgCIgBgDQAAgGADgGQADgGAEgBQAFgBAJAEQALAFACAEIABACIgCALQgCAIgCAAIgBABQgEAAgKgFg");
	this.shape_34.setTransform(411.3,146.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#0033CC").s().p("AghBUQgKgCgBgCQgDgDACgEIACgCIACgDIAAiLIgCgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgEAFgBQAEgBALADQANADABADQABADgBAEQgCAEAAAHIAAAlQALgOAJAAQAHAAALAFQAKAEACAEQADAHABAVQACAYAAApQACAFgBADQgBAGgDACIgFAAQgHAAgKgCQgJgCgCgCIgBgCIACgGIADgEQABgCAAgDQAAg0gBgZQgDgBgKAPQgLAPAAAKIAAAsQAEAEgBAFQgCAGgFACIgCABQgGAAgKgDg");
	this.shape_35.setTransform(403.9,145.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#0033CC").s().p("AAPBWQgHAAgJgCQgOgDgCgDQgDgEADgGQADgFAAgCIAAhhIgOADIgEACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgEgBgIgLQgIgKABgEQABgFAIgCIAFAAIAFAAIBEgSIAGgDQADgBADAAQAFABACAEIADAJQACAIAAAFIgBAHQgBACgGABIgEgCQgDgBgCAAIgVAGIAABnQAAAGADAHIAAAHQgBAHgDABIgCAAg");
	this.shape_36.setTransform(393.2,145.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[]},26).to({state:[]},2).wait(76));

	// Question
	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6633CC").s().p("AgTCBQgGgBgIgGQgIgGgKgKQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAAAABgBIABgCIAEgKQADgHAAgGQAAgEADgCQAEgDAFAAQAHAAAMAKQAMAKABAFIAAADQAAACgCAEIgFAHIgEALQgDAIgFAAIAAAAgAgWAzQgEgBgIgGQgHgGgJgMIgBgDQAAgFAEgGQAGgIAcgVQAagYAKgNQARgUgJgMQgFgGgLAAQgSAAggASIgCAAQgEAAgJgJQgHgIgFgIQgCgEAEgFQAEgFATgHIAVgGQAKgCAIAAQAIAAAHACQAGABAGADQAfATAEAqQABAYgPATQgQASgRALQgXAXgGAJQgFAIgEAAIgBAAg");
	this.shape_37.setTransform(493.1,124.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6633CC").s().p("AgQBRQgTgGgGgIQgRgXAAgmQAAgiAPgcQAIgPAKgIQAKgIAMgBQAIAAAMAGIAPAHIALAJQADACACANQADAOAAAOQAAAKgCAGQgBAHgEACQgOAFgQACQgOADgOABQgBAOAEAQQAEAQAEAAQAEAAAJgKQAHgJABgFIAGgSQAFgBANAGQAOAFACAEQADAEgOAVQgIAMgHAIQgHAIgIAEIgFABQgLAAgRgIgAgFgpIgHAQIgEAQQANgBAGgGQADgBABgIIABgUQAAgLgBAAIAAAAQgFAAgHAPg");
	this.shape_38.setTransform(479.8,127.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6633CC").s().p("AAAB4QgQgEgDgDQgHgFABgFIABgDIABgEIAAjLIgBgDIgBgEQABgHAKgCIAMAAQAJAAAHADQANADAAAHIgCAFIgCAFIgDASIAACwQAAADABADIACAEQAAATgGABIgBAAQgEAAgMgEg");
	this.shape_39.setTransform(470,124.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6633CC").s().p("AgqB6IgRgGQgHgCgBgHQgBgCADgJIADgJIAAi7QAAgKgCgCQgEgIACgDQABgCAGAAQAHAAANADIARADQAFABACAGIABAEQAAAMgEAXIAOgbQAIgSAHACQAdAFAOASQAOASAAAdQAAAigSAfQgJARgJALQgKALgLAFIgFABQgEAAgEgEIgPgNIAAA4IACAIIADAJQAAAGgJAAQgHAAgOgEgAgRAhQARgHALgZQANgXAAgVQAAgYgTgDIgBAAQgIAAgNBng");
	this.shape_40.setTransform(459.1,130.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6633CC").s().p("AgqB6IgRgGQgHgCgBgHQgBgCADgJIADgJIAAi7QAAgKgCgCQgEgIACgDQABgCAGAAQAHAAANADIARADQAFABACAGIABAEQAAAMgEAXIAOgbQAIgSAHACQAdAFAOASQAOASAAAdQAAAigSAfQgJARgJALQgKALgLAFIgFABQgEAAgEgEIgPgNIAAA4IACAIIADAJQAAAGgJAAQgHAAgOgEgAgRAhQARgHALgZQANgXAAgVQAAgYgTgDIgBAAQgIAAgNBng");
	this.shape_41.setTransform(443.8,130.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6633CC").s().p("AA9B2QgQgFgFgGQgCgDgDgPQgDgTgEgMQgLABgTAGQgWAHgGAEIgLAfIgCAHQgBAEgEADIgDAAQgHAAgQgHQgRgHAAgDQgBgEAGgQIALgcQgGgGAAgHIAAgCQABgEARgJIAlh+IABgMQgBgJACgBQACgCAFAAQAOAAAXAHIAUAGQAIAEACADQACAfALBBQAPBNAPAfIgBAMQgBAFgCADIgEABQgKAAgOgFgAgDgKQgJAZAAAHQAFgDAYgFIgEgXQgEgTgBgVg");
	this.shape_42.setTransform(426.2,124.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6633CC").s().p("AgZAgQgLgFABgIQgBgJAFACIADABQAJAAAIgIQALgGAAgLIgBgFIgBgGQAAgJAFgDQADgBANAEQANAEACADQACAFABAHQAAAIgEAGQgDAJgGAIQgOARgRABIgCAAQgIAAgIgEg");
	this.shape_43.setTransform(405.2,135.8);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6633CC").s().p("AAoB7IgRgDQgFgBgCgGIAAgEQAAgMADgXIgOAcQgHARgIgBQgdgGgOgSQgOgSAAgdQAAghASghQASghAVgKIAFgCQAGABASARIAAg4IgDgIIgCgJQAAgGAIAAQAHAAAOAEIARAFQAHADABAGQABAEgDAIIgDAKIAAC7QAAAJACACQAEAIgCACQgBADgGAAQgHAAgNgDgAgKAAQgGALgDALQgEALAAALQAAAZATACQAIABAOhnQgQAGgMAZg");
	this.shape_44.setTransform(392.9,124.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6633CC").s().p("AgwBXQgPgEgCgCQgBgCgBgDQAAgDADgEIAEgFIAAiFIgDgGQgCgEABgDQACgGAHgCQAFgBARAFQATAEABAFQABADgBAHIgDALIABAHQAEgOAHgLQAIgOAJAAQALAAAPAHQAQAHACAFQAFAJACAjQACAgAAA7QABAGAAAFQAAAJgGADIgHABQgKAAgOgDQgOgDgDgDIAAgEQgBgDAEgHQAFgHAAgDQAAhKgBgnQgFgCgPAcQgQAdABAMIAAA3QADADAAAGQAAAFgCAEQgDAEgFACIgDABQgIAAgPgEg");
	this.shape_45.setTransform(378.1,127.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6633CC").s().p("AgQBRQgTgGgGgIQgRgXAAgmQAAgiAPgcQAIgPAKgIQAKgIAMgBQAIAAAMAGIAPAHIALAJQADACACANQADAOAAAOQAAAKgCAGQgBAHgEACQgOAFgQACQgOADgOABQgBAOAEAQQAEAQAEAAQAEAAAJgKQAHgJABgFIAGgSQAFgBANAGQAOAFACAEQADAEgOAVQgIAMgHAIQgHAIgIAEIgFABQgLAAgRgIgAgFgpIgHAQIgEAQQANgBAGgGQADgBABgIIABgUQAAgLgBAAIAAAAQgFAAgHAPg");
	this.shape_46.setTransform(364.5,127.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6633CC").s().p("AAQBzQgLAAgNgEQgRgFgCgFQgCgCAEgHQADgEAAgMIAAh4QgEgLAAgDQAAgEALAAQAJAAANAFQAQAGADAEIABADIgDAIQgEAHAAADIAAByQAAADAEAFIADAGQABAKgIADgAgDhIQgWgHgBgDIgBgFQAAgHAEgJQAEgKAGgBQAHgBAPAGQAQAGADAHIAAACQAAAGgCAKQgDALgDACIgBAAQgEAAgSgHg");
	this.shape_47.setTransform(354.4,125.3);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6633CC").s().p("AglBWQgRgGAAgJIACgJQADgGAAgDIAAhxIgDgRQAAgJAIgCIAIgBQAKAAALADQAMADACAEIAAADIgEAOIAAAOIAMgZQAJgQAEAAQAGgCAOAJQANAJABAGQABAEgEADIgHAEIgvBJIAAAwIACAHIABAJQAAAGgEACQgDABgGAAQgLAAgNgEg");
	this.shape_48.setTransform(345.4,127.6);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6633CC").s().p("AgIB1QgSgGgBgFQgBgCADgGQADgHAAgDIAAhlIgKAAQgGAAgIgKQgIgJAAgGQAAgFAEgDQADgDAEAAIAVAAQAAghAEgMQAEgOAJgGQAHgHAPAAIAHAAQAKABAKAJQAJAHABAEQABAEgEAGQgDAFgDAAQgCAAgEgDIgGgDQgNgDAAAbIAAAJIAAAJIAJAAQADAAAKAKQAJAKAAAFQgBAFgDAEQgDAEgEAAIgCAAQgDgCgPAAIAABxQAAACADAEQACADgBADQAAAFgEACQgDADgFAAQgGAAgOgFg");
	this.shape_49.setTransform(333.8,124.5);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#6633CC").s().p("AgSBtQgLgEgFgFQgEgEAAgFQAAgDAEgHIAEgIIAKghIgvhyIgFgFQgEgEgBgIQgBgDAQgKQAQgIAJAAIAEAAQAEADADAHIADANIAXBHIAchJIADgMQACgFAEgCIAHgBQAJAAAMAFQALAEACAFIAAAEQAAAFgEAFIgGAJIg6ClIgBALQgBAJgFABIgDABQgGAAgMgEg");
	this.shape_50.setTransform(313,130.3);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#6633CC").s().p("AhZBXQgPgEgCgCQgBgCAAgDQAAgDADgEIADgFIAAiFIgDgGQgBgEABgDQABgGAHgCQAFgBARAFQATAEACAFQABADgCAHIgEALIABAHQAFgOAIgLQAJgOAKAAQAJAAAQAHQANAHADAFQADAEADARIAOgZQAJgPAKAAQAKAAAPAHQAPAHADAFQAEAJACAjQACAgAAA7QACAGABAFQAAAJgIADIgHABQgJAAgOgDQgOgDgCgDIgCgEQAAgDAEgHQAFgHAAgDQAAhKgCgnQgEgCgPAYQgPAbAAASIAAA5IACAKQgBAHgHAEIgHABQgKAAgLgDQgOgDgDgDIgBgDQgBgDAFgHQAEgIAAgDQABhKgDgnQgEgCgQAcQgRAdAAAMIAAA3QAFADAAAGQAAAFgEAEQgCAEgEACIgEABQgIAAgPgEg");
	this.shape_51.setTransform(293.2,127.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#6633CC").s().p("AgGBpQgSgGgBgFQAAgCACgHQADgGAAgEIAAhkIgKAAQgGAAgIgKQgIgKAAgGQAAgEAEgEQADgDAEAAIAVAAIAAgaQgFgGAAgHQABgGAFgBIAHgBQALAAAMAEQAOADAFADQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAQgBADgEAGIgFAIIAAAQIAKAAQACAAAJAKQAKALAAAEQAAAFgDAEQgEAFgEAAIgBgBQgEgBgPAAIAABwIACAFIACAJQAAAIgMABQgGAAgOgFg");
	this.shape_52.setTransform(269,125.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#6633CC").s().p("AgQBRQgTgGgGgIQgRgXAAgmQAAgiAPgcQAIgPAKgIQAKgIAMgBQAIAAAMAGIAPAHIALAJQADACACANQADAOAAAOQAAAKgCAGQgBAHgEACQgOAFgQACQgOADgOABQgBAOAEAQQAEAQAEAAQAEAAAJgKQAHgJABgFIAGgSQAFgBANAGQAOAFACAEQADAEgOAVQgIAMgHAIQgHAIgIAEIgFABQgLAAgRgIgAgFgpIgHAQIgEAQQANgBAGgGQADgBABgIIABgUQAAgLgBAAIAAAAQgFAAgHAPg");
	this.shape_53.setTransform(256.7,127.9);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#6633CC").s().p("AhZBXQgPgEgCgCQgCgCABgDQAAgDACgEIAEgFIAAiFIgDgGQgCgEABgDQACgGAHgCQAFgBARAFQASAEADAFQABADgCAHIgEALIABAHQAFgOAIgLQAKgOAJAAQAJAAAQAHQANAHADAFQADAEADARIAOgZQAJgPAJAAQALAAAPAHQAPAHADAFQAEAJACAjQACAgAAA7QACAGABAFQAAAJgIADIgHABQgJAAgOgDQgOgDgDgDIgBgEQAAgDAEgHQAFgHAAgDQAAhKgCgnQgEgCgPAYQgPAbAAASIAAA5IABAKQAAAHgHAEIgHABQgKAAgLgDQgOgDgDgDIgBgDQgBgDAFgHQAEgIAAgDQAAhKgBgnQgFgCgQAcQgRAdAAAMIAAA3QAFADAAAGQAAAFgDAEQgDAEgEACIgEABQgIAAgPgEg");
	this.shape_54.setTransform(238.4,127.6);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#6633CC").s().p("AAiBXQgSgEgCgFQgCgEADgGIADgLIgBgHQgFAOgIAMQgEAGgDAEQgFADgFAAQgKAAgPgHQgQgGgCgGQgIgSAAh1QgDgFAAgGQAAgJAHgDIAHgBQAKAAAOADQANADADADIACAEQAAADgFAHQgEAIAAADQgBBwADABQACAAAFgGIALgVQAIgOAFgLQAEgJAAgHIAAg2QgEgEAAgGQAAgFACgEQADgEAFgCIADgBQAIAAAPAEQAPAEACACQACADAAADQAAACgEAEIgDAGIAACEIACAHIACAGQAAAFgJADIgCAAQgGAAgOgEg");
	this.shape_55.setTransform(212.7,127.7);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#6633CC").s().p("AAPBbIgWgFQgNgCgJgDQgIgCgGgHQgHgHgGgMQgEgLgCgNQgCgNAAgOQAAgNACgOQACgOAFgMQAFgNAIgJQAHgKAKgFQADgCAFAAQAGAAAPAEQALAAARADQAJAEAGAHQAGAIAFAMQAHAUAAAdQAAARgDARQgEARgGAPQgIAPgJAHQgIAGgJAAIgDAAgAgFg0QgEAFgEAJQgGAZAAAMQACAZADAOQAGAWAGACQAIACAHgXQAHgWAAgZQAAgPgEgOQgFgWgLAAQgBAAgEAFg");
	this.shape_56.setTransform(198.5,127.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#6633CC").s().p("AgSBtQgLgEgFgFQgEgEAAgFQAAgDAEgHIAEgIIAKghIgvhyIgFgFQgEgEgBgIQgBgDAQgKQAQgIAJAAIAEAAQAEADADAHIADANIAXBHIAchJIADgMQACgFAEgCIAHgBQAJAAAMAFQALAEACAFIAAAEQAAAFgEAFIgGAJIg6ClIgBALQgBAJgFABIgDABQgGAAgMgEg");
	this.shape_57.setTransform(183.4,130.3);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#6633CC").s().p("AgQBRQgTgGgGgIQgRgXAAgmQAAgiAPgcQAIgPAKgIQAKgIAMgBQAIAAAMAGIAPAHIALAJQADACACANQADAOAAAOQAAAKgCAGQgBAHgEACQgOAFgQACQgOADgOABQgBAOAEAQQAEAQAEAAQAEAAAJgKQAHgJABgFIAGgSQAFgBANAGQAOAFACAEQADAEgOAVQgIAMgHAIQgHAIgIAEIgFABQgLAAgRgIgAgFgpIgHAQIgEAQQANgBAGgGQADgBABgIIABgUQAAgLgBAAIAAAAQgFAAgHAPg");
	this.shape_58.setTransform(161.6,127.9);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#6633CC").s().p("AgHBaQgZgHgCgEQgCgCAAgEIAAgGQgOgqgGgZQgHghgDgoIgBgEIAAgGQAAgHAFgCQADAAAUAEQATAFACAEIABAEIgCAHIgCAGIAGAoQAFAaAHAWQACgRALgvIALgmIABgLQACgGAGgBQADgBAPAGQARAHADAGQgLAdgPA5QgNA1ABAHIAAAOQgBAKgGABIgCABQgIAAgUgGg");
	this.shape_59.setTransform(147.8,127.9);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#6633CC").s().p("AgjBVIgLgLIgPgRQgGgIAAgHIAAgFQADgNAJgMQAIgMAOgJQAVgRAlgTQAAgJgFgCQgDgCgRAIQgQAIgHAGIgHAGQgFADgEgBQgDgBgLgJQgKgKgBgDQgCgIAHgEIALgEIAWgLIAVgIQAHgDAIgBQAHAAAIAHIAQANIAPANQAKAIAAAIIAABrIACAKQAAAEgDADQgEADgDAAQgSgDgLgDQgKgEgCgEIAAgCIABgDIACgEIABgCIAAgKQgDACgHAMQgHAMgEAFQgJAJgMAAQgHAAgHgGgAgBAJIgPASQgGAGgFAKQgGAJAAAFQAAAAAAABQAAAAABABQAAAAAAAAQABAAAAAAQADAAAHgGIASgUIAPgXQAHgKADgGQgOAFgJAKg");
	this.shape_60.setTransform(133,127.8);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#6633CC").s().p("AAcB3IgNgIQgGgEgBgDIgBgIQgBgCACgEIADgEIAAg7IgTAFIgWAFIAAA7IACAFIACAEIgCAJQgBAEgCAAQgFACgWgHQgUgHgCgEIAAgHIAAgIIAAi4IADgQQAAgDAKgFIADAAQALAAAMADQAPAFABAHQABADgDAHIgDAKIAABHIApgKIAAhRIgBgFQgBgDAAgDQACgFAHgBIANgCQAGgBANAFQAMAFABAFQABACgCAEIgCAIIAABQIANAMQAJAFgBAEQAAAEgHAGQgGAGgDAAIgFAAIAABJIADALQACASgGADIgFABQgKAAgQgHg");
	this.shape_61.setTransform(117.5,124.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37}]},42).to({state:[]},34).wait(28));

	// Intro
	this.text = new cjs.Text("Hello!", "bold 50px 'Marker Felt'", "#FF13DD");
	this.text.lineHeight = 59;
	this.text.lineWidth = 141;
	this.text.setTransform(36.1,39);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(12).to({_off:true},10).wait(82));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(336.1,189,551.3,206.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;